from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime, timedelta
import pandas as pd
from sqlalchemy import create_engine
import os

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2024, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

def get_db_engine():
    """Create SQLAlchemy engine for database connection."""
    return create_engine(
        f"postgresql+psycopg2://{os.getenv('POSTGRES_USER', 'airflow')}:"
        f"{os.getenv('POSTGRES_PASSWORD', 'airflow')}@"
        f"{os.getenv('POSTGRES_HOST', 'postgres')}:"
        f"{os.getenv('POSTGRES_PORT', '5432')}/shopzada"
    )

def populate_dim_product(**context):
    """Populate dim_product dimension table from ODS with surrogate keys."""
    engine = get_db_engine()
    
    print("=" * 70)
    print("POPULATING DIM_PRODUCT (KIMBALL DIMENSION)")
    print("=" * 70)
    
    conn = engine.raw_connection()
    cursor = conn.cursor()
    
    # Check if ODS has data
    cursor.execute("SELECT COUNT(*) FROM ods.core_products;")
    ods_count = cursor.fetchone()[0]
    print(f"Products in ODS: {ods_count:,}")
    
    if ods_count == 0:
        print("  ⚠ WARNING: No data in ods.core_products!")
        print("  → Please run populate_core_products DAG first")
        cursor.close()
        conn.close()
        raise ValueError("No data in ODS. Run populate_core_products first.")
    
    # Truncate dimension table
    print("\nTruncating dimension table...")
    try:
        cursor.execute("TRUNCATE TABLE dw.dim_product RESTART IDENTITY CASCADE;")
        conn.commit()
        print("  ✓ dw.dim_product truncated (surrogate keys reset)")
    except Exception as e:
        print(f"  ⚠ Error truncating table: {str(e)}")
        conn.rollback()
    
    # Read products from ODS
    print("\n--- Reading from ODS ---")
    products_df = pd.read_sql("""
        SELECT 
            product_id,
            product_name,
            product_type,
            price
        FROM ods.core_products
        ORDER BY product_id
    """, engine)
    
    print(f"Read {len(products_df)} products from ODS")
    
    if len(products_df) == 0:
        print("\n✗ ERROR: No products in ODS!")
        cursor.close()
        conn.close()
        raise ValueError("No products to load to dimension")
    
    # Show sample data
    print("\nSample products to be loaded:")
    print(products_df.head(3).to_string())
    
    # Load to dimension table
    print(f"\n--- Loading to dw.dim_product ---")
    print(f"Loading {len(products_df)} products")
    print("Note: product_key (surrogate key) will be auto-generated by SERIAL")
    
    products_inserted = 0
    products_skipped = 0
    
    for idx, row in products_df.iterrows():
        try:
            cursor.execute("""
                INSERT INTO dw.dim_product 
                (product_id, product_name, product_type, price)
                VALUES (%s, %s, %s, %s)
            """, (
                row['product_id'],
                row['product_name'],
                row['product_type'],
                float(row['price'])
            ))
            conn.commit()
            products_inserted += 1
            
            # Show progress for large datasets
            if products_inserted % 1000 == 0:
                print(f"  Progress: {products_inserted:,} / {len(products_df):,} products")
                
        except Exception as row_error:
            conn.rollback()
            products_skipped += 1
            if products_skipped <= 3:
                print(f"  ⚠ Error inserting product {row['product_id']}: {str(row_error)}")
    
    print(f"\n✓ Products inserted: {products_inserted:,}")
    if products_skipped > 0:
        print(f"  ⚠ Products skipped: {products_skipped:,}")
    
    cursor.close()
    conn.close()
    
    print("=" * 70)

def verify_dimension(**context):
    """Verify the dimension table and show surrogate key mapping."""
    engine = get_db_engine()
    conn = engine.raw_connection()
    cursor = conn.cursor()
    
    print("=" * 70)
    print("DIMENSION VERIFICATION")
    print("=" * 70)
    
    # Dimension stats
    cursor.execute("SELECT COUNT(*) FROM dw.dim_product;")
    dim_count = cursor.fetchone()[0]
    
    cursor.execute("""
        SELECT 
            COUNT(*) as total_products,
            COUNT(DISTINCT product_type) as unique_types,
            AVG(price) as avg_price,
            MIN(price) as min_price,
            MAX(price) as max_price,
            MIN(product_key) as min_surrogate_key,
            MAX(product_key) as max_surrogate_key
        FROM dw.dim_product;
    """)
    stats = cursor.fetchone()
    
    print(f"\ndw.dim_product Statistics:")
    print(f"  Total products: {dim_count:,}")
    
    if stats and stats[0] and stats[0] > 0:
        print(f"  Unique product types: {stats[1]}")
        print(f"  Average price: ${stats[2]:.2f}" if stats[2] else "  Average price: $0.00")
        print(f"  Price range: ${stats[3]:.2f} - ${stats[4]:.2f}" if stats[3] and stats[4] else "  Price range: N/A")
        print(f"  Surrogate key range: {stats[5]} to {stats[6]}")
    
    # Show product type distribution
    cursor.execute("""
        SELECT product_type, COUNT(*) as count
        FROM dw.dim_product
        GROUP BY product_type
        ORDER BY count DESC
        LIMIT 10;
    """)
    
    print("\n  Product Type Distribution:")
    for row in cursor.fetchall():
        print(f"    {row[0]}: {row[1]:,} products")
    
    # Show surrogate key mapping examples
    cursor.execute("""
        SELECT product_key, product_id, product_name, product_type, price
        FROM dw.dim_product
        ORDER BY product_key
        LIMIT 10;
    """)
    
    print("\n  Sample Surrogate Key Mapping:")
    print("  " + "-" * 90)
    print(f"  {'SK':>5} | {'Business Key':<15} | {'Product Name':<30} | {'Type':<15} | {'Price':>8}")
    print("  " + "-" * 90)
    
    for row in cursor.fetchall():
        product_key = row[0]
        product_id = row[1]
        product_name = row[2][:30]  # Truncate long names
        product_type = row[3][:15]
        price = row[4]
        print(f"  {product_key:>5} | {product_id:<15} | {product_name:<30} | {product_type:<15} | ${price:>7.2f}")
    
    print("  " + "-" * 90)
    
    # Explain the surrogate key concept
    print("\n  ℹ️  About Surrogate Keys:")
    print("     - product_key is an auto-generated surrogate key (SERIAL)")
    print("     - product_id is the natural/business key from source systems")
    print("     - Fact tables will reference product_key (not product_id)")
    print("     - This allows tracking history and handling changes (SCD Type 2)")
    
    cursor.close()
    conn.close()
    
    print("=" * 70)
    print("DIM_PRODUCT POPULATION COMPLETE")
    print("=" * 70)
    print("\nNext Steps:")
    print("  1. Wait for other departments' data (customer, enterprise, marketing)")
    print("  2. Populate other dimensions (dim_user, dim_merchant, etc.)")
    print("  3. Then populate fact tables (fact_sales, fact_orders, etc.)")
    print("=" * 70)

with DAG(
    'populate_dim_product',
    default_args=default_args,
    description='Populate dim_product dimension table in data warehouse from ODS',
    schedule_interval=None,
    catchup=False,
    tags=['dw', 'kimball', 'dimension', 'product', 'ods-to-dw'],
) as dag:
    
    populate_task = PythonOperator(
        task_id='populate_dim_product',
        python_callable=populate_dim_product,
    )
    
    verify_task = PythonOperator(
        task_id='verify_dimension',
        python_callable=verify_dimension,
    )
    
    populate_task >> verify_task